### ISSUE TITLE
Unable to load Doom64Hack.asi. Error: 126

### ISSUE THREAD

**Issue by randomname42** [SuiMachine/Doom-64-Sui-s-Hack#2]
I get this message every time I start Doom 64 with the hack installed:

ASI Loader
---------------------------
Unable to load Doom64Hack.asi. Error: 126

I put the version.dll and scripts folder into the folder with DOOM64_x64.exe

The error pops up even if I change all options in Doom64Hack.ini to false. The hack being in place by just itself still has the error.

The game still starts after closing the error, but he error seems to make the hack not work at all. If I turn on the Y axis hack for example, moving the mouse up or down does nothing in game.

I don't care about mouselook myself but I did really want to use the baron damage fix.

In case it's a factor, I did fix the chaingun offset and put the original health sprites into DOOM64.wad itself. But I don't see any way that should have an effect on the hack.

**Comment by SuiMachine** [comment]
Interesting. Can you install CFF Explorer Suite (https://ntcore.com/?page_id=388), rename Doom64Hack.asi to Doom64Hack.dll and check Dependency walker on what it tags (as in if any of NSVCO140.dll or VCRUNTIME libraries are shown as missing) - maybe it's just some redist library missing.

If not, 2nd guess is that it might be antivirus or something or that sort blocking it. Asi files (which are essentially dll libraries) get loaded with asi loader regardless of what settings are set, since the code for actually setting properties is handled after they are loaded into memory and its DllMain function gets executed.

**Comment by randomname42** [comment]
Is everything with a red dot tagged? Because there are a ton of things listed that have red dots on them, but most of them are called api-ms-win-crt-X-|1-1-0.dll, where X is a different word, like stdio, string, filesystem, etc.

There's also a VCRUNTIME140_1.dll with a red dot on it. I don't know why that's there considering there's a VCRUNTIME140.dll with no red dot on it.

![dep_d64hack](https://user-images.githubusercontent.com/31464072/88027635-2b499280-cafd-11ea-86d3-aea12f0bdfca.jpg)

If I expand the lists the amount of things tagged becomes ridiculous. For simplicity I'll post some screenshots of exactly what it's showing me.

![dep_kernel32](https://user-images.githubusercontent.com/31464072/88027656-31d80a00-cafd-11ea-935a-6e438bdc40aa.jpg)

![dep_user32](https://user-images.githubusercontent.com/31464072/88027696-3ef4f900-cafd-11ea-8349-9002a9c69725.jpg)

![dep_msvcp140](https://user-images.githubusercontent.com/31464072/88027718-4916f780-cafd-11ea-9771-62c516f57e38.jpg)

![dep_vcruntime140](https://user-images.githubusercontent.com/31464072/88027739-5338f600-cafd-11ea-9d1d-f192178a384d.jpg)

**Comment by SuiMachine** [comment]
I'd not worry about the api-ms-win-core. My guess is - the reason it fails to load is **VCRUNTIME140_1.dll**, which I assume is a part of Visual Studio 2019 redist. Just to be sure, I've installed the older platform toolset and compiled it using VS2017, which doesn't add that library as a dependency - https://github.com/SuiMachine/Doom-64-Sui-s-Hack/releases/latest

Alternatively, you may want to try installing the VC redist from Microsoft - https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by randomname42** [comment]
Yep, that fixed it. It loads now without an error, and the y axis hack is working in game so the hack is definitely taking effect now too.
